### ISSUE TITLE
Removal of a data object fails with SYS_NO_GOOD_REPLICA if no good replica exists on the file

### ISSUE THREAD

**Issue by JustinKyleJames** [irods/irods_rule_engine_plugin_logical_quotas#122] opened 2024-12-11 16:03 UTC
A consortium member tried to remove a data object which only had a stale replica on it.  This resulted in a SYS_NO_GOOD_REPLICA error and the stale replica was not deleted.

When we disabled logical quotas, the removal of the data object succeeded.

**Comment by korydraughn** [comment] 2024-12-11 16:27
Noting here that @alanking mentioned that the following function could be related:

https://github.com/irods/irods_rule_engine_plugin_logical_quotas/blob/c7e9dd756d43b8bbcdd2c6a669620d2cb2442f62/src/handler.cpp#L1217-L1265

**Comment by alanking** [comment] 2024-12-11 16:36
This is a duplicate of https://github.com/irods/irods_rule_engine_plugin_logical_quotas/issues/111. The issue was fixed in 4.3.2.0. Closing this one.

For reference, here's what that same method looked like before #111 was resolved (notice: `SYS_NO_GOOD_REPLICA` is not being handled):
https://github.com/irods/irods_rule_engine_plugin_logical_quotas/blob/4.3.1.0/src/handler.cpp#L1184-L1210

**Closed by alanking** 2024-12-11 16:36 UTC
Labels: bug, duplicate, consortium-member
