### ISSUE TITLE
test for issue #35 failing on main branch

### ISSUE THREAD

**Issue by d-w-moore** [irods/irods_rule_engine_plugin_logical_quotas#90] opened 2023-03-20 19:55 UTC
The failing test is: `test_group_owned_collections_do_not_require_the_admin_to_manually_change_acls__issue_35`

The failure was discovered while running the test suite for  https://github.com/irods/irods_rule_engine_plugin_logical_quotas/pull/89, but still fails when the changes are reverted. See the dev branch [84.m-DEBUG](https://github.com/d-w-moore/irods_rule_engine_plugin_logical_quotas/tree/84.m-DEBUG) for a place to start an investigation, as it contains a reverting commit for the changes in the previously mentioned PR. This branch should be compiled against the `irods/irods` repo  post-4.3.0 / pre-4.3.1 main branch from ~ Mar. 20, 2023.

Sample session showing the run and output of the test:
```
irods@prec3431:~/scripts$ python3  run_tests.py --run_s test_rule_engine_plugin_logical_quotas.Test_Rule_Engine_Plugin_Logical_Quotas.test_group_owned_collections_do_not_require_the_admin_to_manually_change_acls__issue_35
irods.test.test_rule_engine_plugin_logical_quotas.Test_Rule_Engine_Plugin_Logical_Quotas.test_group_owned_collections_do_not_require_the_admin_to_manually_change_acls__issue_35 ... FAIL

Stdout:
 --- IrodsSession: icommand executed by [rods#tempZone] [iinit] --- 
Assert Command: iinit
Expecting STDOUT_SINGLELINE: ['']
  stdout:
    | WARNING: Error 25 disabling echo mode. Password will be displayed in plaintext.
    | Enter your current iRODS password:
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [rods#tempZone] [iinit] --- 
Assert Command: iinit
Expecting STDOUT_SINGLELINE: ['']
  stdout:
    | WARNING: Error 25 disabling echo mode. Password will be displayed in plaintext.
    | Enter your current iRODS password:
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [rods#tempZone] [iadmin mkuser otherrods rodsadmin] --- 
Assert Command: iadmin mkuser otherrods rodsadmin
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [rods#tempZone] [iadmin moduser otherrods password rods] --- 
Assert Command: iadmin moduser otherrods password rods
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [otherrods#tempZone] [iinit] --- 
Assert Command: iinit
Expecting STDOUT_SINGLELINE: ['']
  stdout:
    | WARNING: Error 25 disabling echo mode. Password will be displayed in plaintext.
    | Enter your current iRODS password:
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [otherrods#tempZone] [imkdir /tempZone/home/otherrods/2023-03-20Z19:30:07--irods-testing-uhx75a8i] --- 
Assert Command: imkdir /tempZone/home/otherrods/2023-03-20Z19:30:07--irods-testing-uhx75a8i
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [otherrods#tempZone] [icd /tempZone/home/otherrods/2023-03-20Z19:30:07--irods-testing-uhx75a8i] --- 
Assert Command: icd /tempZone/home/otherrods/2023-03-20Z19:30:07--irods-testing-uhx75a8i
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [rods#tempZone] [iinit] --- 
Assert Command: iinit
Expecting STDOUT_SINGLELINE: ['']
  stdout:
    | WARNING: Error 25 disabling echo mode. Password will be displayed in plaintext.
    | Enter your current iRODS password:
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [rods#tempZone] [iadmin mkuser anotherrods rodsadmin] --- 
Assert Command: iadmin mkuser anotherrods rodsadmin
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [rods#tempZone] [iadmin moduser anotherrods password rods] --- 
Assert Command: iadmin moduser anotherrods password rods
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [anotherrods#tempZone] [iinit] --- 
Assert Command: iinit
Expecting STDOUT_SINGLELINE: ['']
  stdout:
    | WARNING: Error 25 disabling echo mode. Password will be displayed in plaintext.
    | Enter your current iRODS password:
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [anotherrods#tempZone] [imkdir /tempZone/home/anotherrods/2023-03-20Z19:30:07--irods-testing-uej31334] --- 
Assert Command: imkdir /tempZone/home/anotherrods/2023-03-20Z19:30:07--irods-testing-uej31334
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [anotherrods#tempZone] [icd /tempZone/home/anotherrods/2023-03-20Z19:30:07--irods-testing-uej31334] --- 
Assert Command: icd /tempZone/home/anotherrods/2023-03-20Z19:30:07--irods-testing-uej31334
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [rods#tempZone] [iinit] --- 
Assert Command: iinit
Expecting STDOUT_SINGLELINE: ['']
  stdout:
    | WARNING: Error 25 disabling echo mode. Password will be displayed in plaintext.
    | Enter your current iRODS password:
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [rods#tempZone] [iadmin mkuser alice rodsuser] --- 
Assert Command: iadmin mkuser alice rodsuser
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [rods#tempZone] [iadmin moduser alice password apass] --- 
Assert Command: iadmin moduser alice password apass
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [alice#tempZone] [iinit] --- 
Assert Command: iinit
Expecting STDOUT_SINGLELINE: ['']
  stdout:
    | WARNING: Error 25 disabling echo mode. Password will be displayed in plaintext.
    | Enter your current iRODS password:
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [alice#tempZone] [imkdir /tempZone/home/alice/2023-03-20Z19:30:08--irods-testing-a17h9p3q] --- 
Assert Command: imkdir /tempZone/home/alice/2023-03-20Z19:30:08--irods-testing-a17h9p3q
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [alice#tempZone] [icd /tempZone/home/alice/2023-03-20Z19:30:08--irods-testing-a17h9p3q] --- 
Assert Command: icd /tempZone/home/alice/2023-03-20Z19:30:08--irods-testing-a17h9p3q
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [otherrods#tempZone] [iadmin asq select count(distinct data_id) from R_DATA_MAIN d inner join R_COLL_MAIN c on d.coll_id = c.coll_id where coll_name like ? logical_quotas_count_data_objects_recursive] --- 
Assert Command: iadmin asq select count(distinct data_id) from R_DATA_MAIN d inner join R_COLL_MAIN c on d.coll_id = c.coll_id where coll_name like ? logical_quotas_count_data_objects_recursive
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [otherrods#tempZone] [iadmin asq select sum(t.data_size) from (select data_id, data_size from R_DATA_MAIN d inner join R_COLL_MAIN c on d.coll_id = c.coll_id where coll_name like ? and data_is_dirty in ('1', '4') group by data_id, data_size) as t logical_quotas_sum_data_object_sizes_recursive] --- 
Assert Command: iadmin asq select sum(t.data_size) from (select data_id, data_size from R_DATA_MAIN d inner join R_COLL_MAIN c on d.coll_id = c.coll_id where coll_name like ? and data_is_dirty in ('1', '4') group by data_id, data_size) as t logical_quotas_sum_data_object_sizes_recursive
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [otherrods#tempZone] [iadmin mkgroup testgroup_issue_36] --- 
Assert Command: iadmin mkgroup testgroup_issue_36
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [otherrods#tempZone] [ils -A /tempZone/home/testgroup_issue_36] --- 
Assert Command: ils -A /tempZone/home/testgroup_issue_36
Expecting STDOUT: [' ']
  stdout:
    | 
  stderr:
    | Error stat(ing) image file (raw_open: image "/tempZone/home/testgroup_issue_36" - No such file or directory)
Unexpected output on stderr

FAILED TESTING ASSERTION


 --- IrodsSession: icommand executed by [otherrods#tempZone] [iadmin rmgroup testgroup_issue_36] --- 
 --- IrodsSession: icommand executed by [otherrods#tempZone] [iadmin rsq logical_quotas_sum_data_object_sizes_recursive] --- 
Assert Command: iadmin rsq logical_quotas_sum_data_object_sizes_recursive
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [otherrods#tempZone] [iadmin rsq logical_quotas_count_data_objects_recursive] --- 
Assert Command: iadmin rsq logical_quotas_count_data_objects_recursive
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [rods#tempZone] [iinit] --- 
Assert Command: iinit
Expecting STDOUT_SINGLELINE: ['']
  stdout:
    | WARNING: Error 25 disabling echo mode. Password will be displayed in plaintext.
    | Enter your current iRODS password:
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [otherrods#tempZone] [icd] --- 
Assert Command: icd
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [otherrods#tempZone] [irm -rf /tempZone/home/otherrods/2023-03-20Z19:30:07--irods-testing-uhx75a8i] --- 
Assert Command: irm -rf /tempZone/home/otherrods/2023-03-20Z19:30:07--irods-testing-uhx75a8i
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [otherrods#tempZone] [irmtrash] --- 
Assert Command: irmtrash
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [rods#tempZone] [iadmin rmuser otherrods] --- 
Assert Command: iadmin rmuser otherrods
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [anotherrods#tempZone] [icd] --- 
Assert Command: icd
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [anotherrods#tempZone] [irm -rf /tempZone/home/anotherrods/2023-03-20Z19:30:07--irods-testing-uej31334] --- 
Assert Command: irm -rf /tempZone/home/anotherrods/2023-03-20Z19:30:07--irods-testing-uej31334
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [anotherrods#tempZone] [irmtrash] --- 
Assert Command: irmtrash
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [rods#tempZone] [iadmin rmuser anotherrods] --- 
Assert Command: iadmin rmuser anotherrods
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [alice#tempZone] [icd] --- 
Assert Command: icd
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [alice#tempZone] [irm -rf /tempZone/home/alice/2023-03-20Z19:30:08--irods-testing-a17h9p3q] --- 
Assert Command: irm -rf /tempZone/home/alice/2023-03-20Z19:30:08--irods-testing-a17h9p3q
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [alice#tempZone] [irmtrash] --- 
Assert Command: irmtrash
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [rods#tempZone] [iadmin rmuser alice] --- 
Assert Command: iadmin rmuser alice
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found


======================================================================
FAIL: test_group_owned_collections_do_not_require_the_admin_to_manually_change_acls__issue_35 (irods.test.test_rule_engine_plugin_logical_quotas.Test_Rule_Engine_Plugin_Logical_Quotas)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/irods/scripts/irods/test/test_rule_engine_plugin_logical_quotas.py", line 709, in test_group_owned_collections_do_not_require_the_admin_to_manually_change_acls__issue_35
    _, out, _ = self.admin1.assert_icommand(['ils', '-A', group_home_col], 'STDOUT', [' '])
  File "/var/lib/irods/scripts/irods/test/session.py", line 164, in assert_icommand
    return assert_command(*args, **kwargs)
  File "/var/lib/irods/scripts/irods/test/command.py", line 77, in assert_command
    return _assert_helper(*args, should_fail=False, **kwargs)
  File "/var/lib/irods/scripts/irods/test/command.py", line 105, in _assert_helper
    assert result
AssertionError

Stdout:
 --- IrodsSession: icommand executed by [rods#tempZone] [iinit] --- 
Assert Command: iinit
Expecting STDOUT_SINGLELINE: ['']
  stdout:
    | WARNING: Error 25 disabling echo mode. Password will be displayed in plaintext.
    | Enter your current iRODS password:
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [rods#tempZone] [iinit] --- 
Assert Command: iinit
Expecting STDOUT_SINGLELINE: ['']
  stdout:
    | WARNING: Error 25 disabling echo mode. Password will be displayed in plaintext.
    | Enter your current iRODS password:
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [rods#tempZone] [iadmin mkuser otherrods rodsadmin] --- 
Assert Command: iadmin mkuser otherrods rodsadmin
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [rods#tempZone] [iadmin moduser otherrods password rods] --- 
Assert Command: iadmin moduser otherrods password rods
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [otherrods#tempZone] [iinit] --- 
Assert Command: iinit
Expecting STDOUT_SINGLELINE: ['']
  stdout:
    | WARNING: Error 25 disabling echo mode. Password will be displayed in plaintext.
    | Enter your current iRODS password:
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [otherrods#tempZone] [imkdir /tempZone/home/otherrods/2023-03-20Z19:30:07--irods-testing-uhx75a8i] --- 
Assert Command: imkdir /tempZone/home/otherrods/2023-03-20Z19:30:07--irods-testing-uhx75a8i
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [otherrods#tempZone] [icd /tempZone/home/otherrods/2023-03-20Z19:30:07--irods-testing-uhx75a8i] --- 
Assert Command: icd /tempZone/home/otherrods/2023-03-20Z19:30:07--irods-testing-uhx75a8i
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [rods#tempZone] [iinit] --- 
Assert Command: iinit
Expecting STDOUT_SINGLELINE: ['']
  stdout:
    | WARNING: Error 25 disabling echo mode. Password will be displayed in plaintext.
    | Enter your current iRODS password:
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [rods#tempZone] [iadmin mkuser anotherrods rodsadmin] --- 
Assert Command: iadmin mkuser anotherrods rodsadmin
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [rods#tempZone] [iadmin moduser anotherrods password rods] --- 
Assert Command: iadmin moduser anotherrods password rods
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [anotherrods#tempZone] [iinit] --- 
Assert Command: iinit
Expecting STDOUT_SINGLELINE: ['']
  stdout:
    | WARNING: Error 25 disabling echo mode. Password will be displayed in plaintext.
    | Enter your current iRODS password:
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [anotherrods#tempZone] [imkdir /tempZone/home/anotherrods/2023-03-20Z19:30:07--irods-testing-uej31334] --- 
Assert Command: imkdir /tempZone/home/anotherrods/2023-03-20Z19:30:07--irods-testing-uej31334
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [anotherrods#tempZone] [icd /tempZone/home/anotherrods/2023-03-20Z19:30:07--irods-testing-uej31334] --- 
Assert Command: icd /tempZone/home/anotherrods/2023-03-20Z19:30:07--irods-testing-uej31334
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [rods#tempZone] [iinit] --- 
Assert Command: iinit
Expecting STDOUT_SINGLELINE: ['']
  stdout:
    | WARNING: Error 25 disabling echo mode. Password will be displayed in plaintext.
    | Enter your current iRODS password:
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [rods#tempZone] [iadmin mkuser alice rodsuser] --- 
Assert Command: iadmin mkuser alice rodsuser
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [rods#tempZone] [iadmin moduser alice password apass] --- 
Assert Command: iadmin moduser alice password apass
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [alice#tempZone] [iinit] --- 
Assert Command: iinit
Expecting STDOUT_SINGLELINE: ['']
  stdout:
    | WARNING: Error 25 disabling echo mode. Password will be displayed in plaintext.
    | Enter your current iRODS password:
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [alice#tempZone] [imkdir /tempZone/home/alice/2023-03-20Z19:30:08--irods-testing-a17h9p3q] --- 
Assert Command: imkdir /tempZone/home/alice/2023-03-20Z19:30:08--irods-testing-a17h9p3q
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [alice#tempZone] [icd /tempZone/home/alice/2023-03-20Z19:30:08--irods-testing-a17h9p3q] --- 
Assert Command: icd /tempZone/home/alice/2023-03-20Z19:30:08--irods-testing-a17h9p3q
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [otherrods#tempZone] [iadmin asq select count(distinct data_id) from R_DATA_MAIN d inner join R_COLL_MAIN c on d.coll_id = c.coll_id where coll_name like ? logical_quotas_count_data_objects_recursive] --- 
Assert Command: iadmin asq select count(distinct data_id) from R_DATA_MAIN d inner join R_COLL_MAIN c on d.coll_id = c.coll_id where coll_name like ? logical_quotas_count_data_objects_recursive
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [otherrods#tempZone] [iadmin asq select sum(t.data_size) from (select data_id, data_size from R_DATA_MAIN d inner join R_COLL_MAIN c on d.coll_id = c.coll_id where coll_name like ? and data_is_dirty in ('1', '4') group by data_id, data_size) as t logical_quotas_sum_data_object_sizes_recursive] --- 
Assert Command: iadmin asq select sum(t.data_size) from (select data_id, data_size from R_DATA_MAIN d inner join R_COLL_MAIN c on d.coll_id = c.coll_id where coll_name like ? and data_is_dirty in ('1', '4') group by data_id, data_size) as t logical_quotas_sum_data_object_sizes_recursive
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [otherrods#tempZone] [iadmin mkgroup testgroup_issue_36] --- 
Assert Command: iadmin mkgroup testgroup_issue_36
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [otherrods#tempZone] [ils -A /tempZone/home/testgroup_issue_36] --- 
Assert Command: ils -A /tempZone/home/testgroup_issue_36
Expecting STDOUT: [' ']
  stdout:
    | 
  stderr:
    | Error stat(ing) image file (raw_open: image "/tempZone/home/testgroup_issue_36" - No such file or directory)
Unexpected output on stderr

FAILED TESTING ASSERTION


 --- IrodsSession: icommand executed by [otherrods#tempZone] [iadmin rmgroup testgroup_issue_36] --- 
 --- IrodsSession: icommand executed by [otherrods#tempZone] [iadmin rsq logical_quotas_sum_data_object_sizes_recursive] --- 
Assert Command: iadmin rsq logical_quotas_sum_data_object_sizes_recursive
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [otherrods#tempZone] [iadmin rsq logical_quotas_count_data_objects_recursive] --- 
Assert Command: iadmin rsq logical_quotas_count_data_objects_recursive
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [rods#tempZone] [iinit] --- 
Assert Command: iinit
Expecting STDOUT_SINGLELINE: ['']
  stdout:
    | WARNING: Error 25 disabling echo mode. Password will be displayed in plaintext.
    | Enter your current iRODS password:
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [otherrods#tempZone] [icd] --- 
Assert Command: icd
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [otherrods#tempZone] [irm -rf /tempZone/home/otherrods/2023-03-20Z19:30:07--irods-testing-uhx75a8i] --- 
Assert Command: irm -rf /tempZone/home/otherrods/2023-03-20Z19:30:07--irods-testing-uhx75a8i
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [otherrods#tempZone] [irmtrash] --- 
Assert Command: irmtrash
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [rods#tempZone] [iadmin rmuser otherrods] --- 
Assert Command: iadmin rmuser otherrods
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [anotherrods#tempZone] [icd] --- 
Assert Command: icd
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [anotherrods#tempZone] [irm -rf /tempZone/home/anotherrods/2023-03-20Z19:30:07--irods-testing-uej31334] --- 
Assert Command: irm -rf /tempZone/home/anotherrods/2023-03-20Z19:30:07--irods-testing-uej31334
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [anotherrods#tempZone] [irmtrash] --- 
Assert Command: irmtrash
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [rods#tempZone] [iadmin rmuser anotherrods] --- 
Assert Command: iadmin rmuser anotherrods
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [alice#tempZone] [icd] --- 
Assert Command: icd
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [alice#tempZone] [irm -rf /tempZone/home/alice/2023-03-20Z19:30:08--irods-testing-a17h9p3q] --- 
Assert Command: irm -rf /tempZone/home/alice/2023-03-20Z19:30:08--irods-testing-a17h9p3q
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [alice#tempZone] [irmtrash] --- 
Assert Command: irmtrash
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [rods#tempZone] [iadmin rmuser alice] --- 
Assert Command: iadmin rmuser alice
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found


----------------------------------------------------------------------
Ran 1 test in 2.186s

FAILED (failures=1)
<__main__.RegisteredTestResult run=1 errors=0 failures=1>

```

**Comment by d-w-moore** [comment] 2023-03-21 13:54
Maybe  #35 should contain a note of its mention.

**Comment by alanking** [comment] 2023-03-21 16:05
Is this an issue for 4.3.0.x or 4.2.11.x releases? What about 4.2.12.0?

"I don't know" is an okay answer. Just something for the assignee to consider when working on this.

**Comment by korydraughn** [comment] 2023-03-21 16:07
This is a 4.3 only issue. @d-w-moore did not encounter this in 4.2.11.

**Comment by d-w-moore** [comment] 2023-03-21 16:12
> This is a 4.3 only issue. @d-w-moore did not encounter this in 4.2.11.

Correct

**Comment by korydraughn** [comment] 2024-04-21 15:27
I've watched the reported test pass consistently at the bench for tip of main (b285ba0).

I've also seen the full test suite pass (w/ some minor unrelated tweaks to tests).

I believe things are working as intended. Closing.

**Closed by korydraughn** 2024-04-21 15:27 UTC
Labels: bug
